PosDiff Cut Definition
XENON1T/lax pull request #111
Opened 2017-12-01 21:27 UTC by weiyuehuan

Note:
https://xe1t-wiki.lngs.infn.it/doku.php?id=xenon:xenon1t:analysis:sr1:pos_cut_v0

2017-12-01 21:32 UTC, coderdj requested changes
Thanks! Can you also put this in SR1 (just calling the SR0 version, as done for some other cuts). It probably should go in the lichen lists too. Maybe for low energy all sources.

2017-12-01 21:32 UTC, coderdj commented on lax/lichens/sciencerun0.py
> +                                  + (df['x_observed_nn'] - df['x_observed_tpf'])**2 < 6)
I think this should by 'y' right?

2017-12-01 21:32 UTC, coderdj commented on lax/lichens/sciencerun0.py
> +    This cut is defined for removeing the events with large position difference between NN and TPF alogrithm,
removeing --> removing

2017-12-02 17:37 UTC, sreichard approved these changes

2017-12-02 17:38 UTC, merged