Possible change to PosDiff
XENON1T/lax pull request #120
Opened 2017-12-13 21:05 UTC by zhut19

This is an attempt to make the PosDiff cut a bit more reasonable, by 1) Integrating R square and D square cut together. 2) Add S2 area dependence to the D square upper limit.

2017-12-13 21:11 UTC, zhut19 commented
To visualize the old cut, here we reparameterized the data, into the figure following, that we have R square cut in black lines, and D square cut in red line. And we realized 

A) The R square cut is cutting into signals at high radius, while overlapping D square cut in low radius.
B) The nn is systematically construct outwards, and oscillating relative to tpf
<img width="775" alt="pos_diff_0" src="https://user-images.githubusercontent.com/16232525/33962667-54c5cd06-e020-11e7-9f65-e1e62cb47249.png">

2017-12-13 21:14 UTC, zhut19 commented
One obvious improvement is to remove R square cut and recenter the Rnn - Rtpf to center around 0 by subtracting the purple line in figure above. Thus we can get the plot below.
<img width="775" alt="pos_diff_1" src="https://user-images.githubusercontent.com/16232525/33962783-b0f75cca-e020-11e7-873c-fa47d1d7e08c.png">

2017-12-13 21:18 UTC, zhut19 commented
Once we reduce the position parameter to just adjusted distance between nn tpf position, we can look at the S2 area dependence clearly, and only cut on D and S2 area space. The result is following, also we examine the same Rn220 leakage events we saw before shown in [note](https://xe1t-wiki.lngs.infn.it/doku.php?id=xenon:xenon1t:analysis:sr1:pos_cut_v0).

<img width="802" alt="pos_diff_2" src="https://user-images.githubusercontent.com/16232525/33963814-569ca10a-e024-11e7-8818-3d9b24638f0b.png">

<img width="600" alt="pos_diff_5" src="https://user-images.githubusercontent.com/16232525/33962947-39a66872-e021-11e7-9771-adef5b4423ba.png">

2017-12-14 19:30 UTC, pdeperio requested changes

2017-12-14 19:30 UTC, pdeperio commented on lax/lichens/sciencerun0.py
>      Contact: Yuehuan Wei <ywei@physics.ucsd.edu>
Add your contact info and new Wiki note link.

2017-12-24 15:34 UTC, pdeperio approved these changes

2018-01-02 11:26 UTC, merged