Update on S1PatternLikelihood cut
XENON1T/lax pull request #123
Opened 2018-01-04 06:28 UTC by skazama

It was found that previous s1 pattern likelihood is calculated based on observed positions. Because expected PMT hit-patterns are calculated using true interact positions, thus s1 pattern likelihood should also be calculated using field-distortion-corrected positions.
In PositionReconstruction minitrees, there is a variable named "s1_pattern_fit_hax", and the cut is reoptimized based on this variable. Details can be seen in https://xe1t-wiki.lngs.infn.it/doku.php?id=xenon:xenon1t:kazama:s1_pattern_cut_sr1#update_2018_jan_4th

2018-01-04 13:13 UTC, coderdj commented
Hi Shingo. Linked note Figure U.1. Do you mean 'r' instead of 'z'?

I think if we decide to adopt this variable we should rename it 's1_pattern_fit' and keep as default, but that's a hax issue probably.

2018-01-04 20:48 UTC, pdeperio requested changes
I think should be fine to keep this variable name for now so we don't have to change ```Extended``` treemaker and regenerate all those minitrees.

@skazama Can you please cross-check acceptance on SR0 too?

2018-01-05 08:25 UTC, skazama commented
@coderdj  In Fig U.1, it is actually "z" (I divided z-region into two regions). Because field distortion effect in low-z region is more significant than that for top-z region, thus I compared them, but will also check inner and outer region.

2018-01-05 18:31 UTC, pdeperio approved these changes

2018-01-05 18:31 UTC, pdeperio commented
I'm ok to merge, and re-check SR0 acceptance in @sreichard's framework later.

2018-01-05 19:14 UTC, sreichard approved these changes
@pdeperio we can definitely do that

2018-01-05 19:23 UTC, merged