Bug-fix for s1 pattern likelihood cuts
XENON1T/lax pull request #137
Opened 2018-01-24 16:41 UTC by skazama

Dan and Jelle found that dead PMTs are included in the calculation of expected hit-patterns (See [this link](https://github.com/XENON1T/pax/pull/663)), and then cuts are optimized again with bug-fix.

From this version, we decided to use s1 pattern likelihood cut for top and bottom PMT arrays separately as done in XENON100. This is because if we use combined one, information can be smeared due to many PMTs, and the combined variable might be no longer sensitive to rejecting bad events like AC. 

Details can be seen in this [note](https://xe1t-wiki.lngs.infn.it/doku.php?id=xenon:xenon1t:kazama:s1_pattern_cut_sr1#update_2018_jan_24th)

2018-01-24 19:04 UTC, pdeperio commented
Thanks Shingo. Do you have waveforms of those few events that are removed by bottom in SR0?

@feigaodm are you able to show the effect of this new cut (and recent others) on AC model?

2018-01-24 19:05 UTC, pdeperio commented
Thanks Shingo. Do you have waveforms of those few events that are removed by bottom in SR0?

@feigaodm are you able to show the effect of this new cut (and recent others) on AC model?

2018-01-24 19:09 UTC, skazama commented
Waveform for rejected event can be seen [here](https://xe1t-wiki.lngs.infn.it/lib/exe/detail.php?id=xenon%3Axenon1t%3Aanalysis%3Asciencerun1%3Aanomalous_background&media=xenon:xenon1t:analysis:sciencerun1:161229_1548_252278_all.png). If you carefully compare PMT hit pattern for s1 (bottom) and s2 (top), it is clear that s1 hits are clustered bottom left region, which should be top right region from s2 x-y position.

2018-01-25 09:27 UTC, pdeperio requested changes
Please use ```ManyLichen``` to separate the two conditionals so we can easily see the value for both. For example, [MuonVeto cut](https://github.com/XENON1T/lax/blob/c624316940d62fe829b201b7dec103fa57b198f6/lax/lichens/sciencerun0.py#L800).

2018-01-25 10:35 UTC, pdeperio approved these changes

2018-01-25 12:52 UTC, sreichard approved these changes

2018-01-28 07:33 UTC, merged