PosDiff cut v4
XENON1T/lax pull request #138
Opened 2018-01-25 04:45 UTC by weiyuehuan

1) Using 98% quantile of the flat deltaR and D for the cut bounds, quantile defined with S2 in [200, 500]pe and extrapolate to whole range.
2) Using deltaR instead of deltaR^{2} to remove the radius dependence.
3) The details in [note](https://xe1t-wiki.lngs.infn.it/doku.php?id=xenon:xenon1t:analysis:sr1:pos_cut_v4#final_cut_definition)

2018-01-29 15:40 UTC, tunnell approved these changes
Technically good

2018-01-30 00:32 UTC, pdeperio requested changes
Awaiting checks with wall model as [discussed at telecon](https://xe1t-wiki.lngs.infn.it/doku.php?id=xenon:xenon1t:analysis:meetings:20180129)

2018-02-07 12:28 UTC, sreichard approved these changes

2018-02-07 20:01 UTC, weiyuehuan commented
Updated to 99% quantile S2 dependence D cut, with LoneS2 and Rn220 data, cut bound and acceptance shown below:

![posdiffdcut](https://user-images.githubusercontent.com/9466523/35938651-9ecbac4a-0bfe-11e8-8682-a917872a0eaf.png)
![accep_200_400_r](https://user-images.githubusercontent.com/9466523/35938655-a100d896-0bfe-11e8-8c5a-d9ee0d11cefe.png)
![accep_wholerange](https://user-images.githubusercontent.com/9466523/35938658-a2fce0a4-0bfe-11e8-8dc0-902159759b3b.png)

2018-02-07 20:38 UTC, pdeperio approved these changes

2018-02-07 20:39 UTC, merged