Add cS2 AFT cut
XENON1T/lax pull request #142
Opened 2018-02-06 15:44 UTC by adambrown1

Adds a cut on cS2 area fraction top. This has a better resolution than S2 AFT (uncorrected) since it accounts for PMTs which are switched off or set to zero gain in pax in the top array. The two new cuts added are CS2AreaFractionTop, which is a 99% acceptance cut setting an upper and lower bound on the cS2 AFT, and CS2AreaFractionTop96p which is a 96% upper-bound-only cut. Fixes #140 

For now these are not added to the default cuts lists so you must apply them manually.

For more details see the note at https://xe1t-wiki.lngs.infn.it/doku.php?id=xenon:xenon1t:adam:s2aft:sr1_cs2_cut

2018-02-06 23:07 UTC, pdeperio approved these changes

2018-02-07 05:04 UTC, feigaodm requested changes
I thought AFT defined like: cAFT = cS2Top / (cS2Bottom +cS2Top) is a better variable for the cut. Two correction maps are independent of each other by this definition. If we use the one as is, there will be some correlations and probably the rejection of this cut will be worse. I think it's better to check. One or two plots with variable defined as suggested will probably convince me.

2018-02-07 05:07 UTC, feigaodm commented on lax/lichens/sciencerun0.py
> +    class CS2AreaFractionTopLower(StringLichen):
I would argue for a looser acceptance on the lower part. upper part is used against gas events we are most afraid of, so we can tolerate 1-2% acceptance loss. The lower one can be modified so acceptance is almost unity.

2018-02-07 12:26 UTC, sreichard approved these changes

2018-02-07 16:47 UTC, feigaodm approved these changes

2018-02-07 20:42 UTC, merged

2018-02-07 20:51 UTC, feigaodm commented
I checked the distributions in different AFT space. At higher energy (S2 in [1000,1200]PE), we can probably improved a bit by using the parameter I suggested. See this plot based on Lone-S2 sample.
<img width="906" alt="screen shot 2018-02-07 at 11 41 11 am" src="https://user-images.githubusercontent.com/18223253/35940849-832dd150-0c1e-11e8-8c78-1415a911cfa7.png">

At lower energy new threshold (S2 in [200,300]PE), the rejection power of this cut is anyway very limited, so I think it's fine as is and we shall revisit this for S2-only analysis in the future.
<img width="906" alt="200-300pe" src="https://user-images.githubusercontent.com/18223253/35940934-bfe9f894-0c1e-11e8-820e-861408b7ce95.png">

2018-02-08 07:46 UTC, adambrown1 commented
*@feigaodm* From the plot it looks like you are probably correct but I am
not sure I understand why this is obvious. We expect cs2 = cs2_top +
cs2_bottom. If the latter definition is better shall we not change hax to
define cs2_total as the sum?

2018-02-07 21:51 GMT+01:00 Fei Gao <notifications@github.com>:

> I checked the distributions in different AFT space. At higher energy (S2
> in [1000,1200]PE), we can probably improved a bit by using the parameter I
> suggested. See this plot based on Lone-S2 sample.
> [image: screen shot 2018-02-07 at 11 41 11 am]
> <https://user-images.githubusercontent.com/18223253/35940849-832dd150-0c1e-11e8-8c78-1415a911cfa7.png>
>
> At lower energy new threshold (S2 in [200,300]PE), the rejection power of
> this cut is anyway very limited, so I think it's fine as is and we shall
> revisit this for S2-only analysis in the future.
> [image: 200-300pe]
> <https://user-images.githubusercontent.com/18223253/35940934-bfe9f894-0c1e-11e8-820e-861408b7ce95.png>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/XENON1T/lax/pull/142#issuecomment-363906308>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AVKfrp-299gcK3KagjzCTdLtYBoHYxPzks5tSgzXgaJpZM4R7Qst>
> .
>

2018-02-08 10:36 UTC, adambrown1 commented
@feigaodm Now I finally understood. We expect that the cs2_tot = cs2_top + cs2_bottom, but applying the S2_tot correction by itself assumes the usual area fraction top as seen in Krypton data. So for gas events the total correction map is not valid which is what you see in your plots. So I think we should move after SR1 to using the definition cs2_tot = cs2_top + cs2_bottom and remove the total correciton map from hax. For now it should be OK though, and the change for good data should be negligible