Added S1AreaFractionTop
XENON1T/lax pull request #16
Opened 2017-02-27 20:58 UTC by darrylmasson

Adds version 0 of the s1 area fraction top cut. The map is a separate json file that at some point should make its way into pax, but for now Jelle said to push it into lax.

2017-02-27 21:22 UTC, tunnell reviewed
This really needs to make its way into pax... can you do that too?  This should be thought of as temporary.

2017-02-27 21:40 UTC, tunnell requested changes
You need to add scipy to setup.py.

2017-02-27 21:40 UTC, tunnell commented on lax/lichens/sciencerun0.py
> +from pax.InterpolatingMap import InterpolatingMap
Is there a way to *not* use the pax interpolating map?  Scipy interpolate or something?  It's another (big) dependency.

2017-02-27 22:25 UTC, darrylmasson commented on lax/lichens/sciencerun0.py
> +from pax.InterpolatingMap import InterpolatingMap
Scipy doesn't have a multidimension map that both interpolates and extrapolates. In principle we could reimplement the pax map here and strip out the logging features, which should keep the extra dependencies to a minimum until the p-value is computed further up the processing chain.

2017-02-28 00:06 UTC, pdeperio commented on lax/lichens/sciencerun0.py
> +    note: xenon:xenon1t:darryl:xe1t_s1_aft_map
put actual link

2017-03-02 17:42 UTC, tunnell approved these changes

2017-03-02 17:44 UTC, pep8speaks commented
Hello @darrylmasson! Thanks for updating the PR.

 - In the file [`lax/lichens/sciencerun0.py`](https://github.com/darrylmasson/lax/blob/333a5113a6ff3f7a86a58db255edd60fce7af34f/lax/lichens/sciencerun0.py), following are the PEP8 issues :

> [Line 8:1](https://github.com/darrylmasson/lax/blob/333a5113a6ff3f7a86a58db255edd60fce7af34f/lax/lichens/sciencerun0.py#L8): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 9:1](https://github.com/darrylmasson/lax/blob/333a5113a6ff3f7a86a58db255edd60fce7af34f/lax/lichens/sciencerun0.py#L9): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 13:3](https://github.com/darrylmasson/lax/blob/333a5113a6ff3f7a86a58db255edd60fce7af34f/lax/lichens/sciencerun0.py#L13): [E111](https://duckduckgo.com/?q=pep8%20E111) indentation is not a multiple of four
> [Line 14:1](https://github.com/darrylmasson/lax/blob/333a5113a6ff3f7a86a58db255edd60fce7af34f/lax/lichens/sciencerun0.py#L14): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 17:5](https://github.com/darrylmasson/lax/blob/333a5113a6ff3f7a86a58db255edd60fce7af34f/lax/lichens/sciencerun0.py#L17): [E113](https://duckduckgo.com/?q=pep8%20E113) unexpected indentation
> [Line 34:3](https://github.com/darrylmasson/lax/blob/333a5113a6ff3f7a86a58db255edd60fce7af34f/lax/lichens/sciencerun0.py#L34): [E111](https://duckduckgo.com/?q=pep8%20E111) indentation is not a multiple of four
> [Line 35:1](https://github.com/darrylmasson/lax/blob/333a5113a6ff3f7a86a58db255edd60fce7af34f/lax/lichens/sciencerun0.py#L35): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 39:5](https://github.com/darrylmasson/lax/blob/333a5113a6ff3f7a86a58db255edd60fce7af34f/lax/lichens/sciencerun0.py#L39): [E113](https://duckduckgo.com/?q=pep8%20E113) unexpected indentation
> [Line 74:80](https://github.com/darrylmasson/lax/blob/333a5113a6ff3f7a86a58db255edd60fce7af34f/lax/lichens/sciencerun0.py#L74): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (87 > 79 characters)
> [Line 79:80](https://github.com/darrylmasson/lax/blob/333a5113a6ff3f7a86a58db255edd60fce7af34f/lax/lichens/sciencerun0.py#L79): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (86 > 79 characters)
> [Line 110:80](https://github.com/darrylmasson/lax/blob/333a5113a6ff3f7a86a58db255edd60fce7af34f/lax/lichens/sciencerun0.py#L110): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 79 characters)
> [Line 212:80](https://github.com/darrylmasson/lax/blob/333a5113a6ff3f7a86a58db255edd60fce7af34f/lax/lichens/sciencerun0.py#L212): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (93 > 79 characters)
> [Line 214:80](https://github.com/darrylmasson/lax/blob/333a5113a6ff3f7a86a58db255edd60fce7af34f/lax/lichens/sciencerun0.py#L214): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (97 > 79 characters)
> [Line 215:80](https://github.com/darrylmasson/lax/blob/333a5113a6ff3f7a86a58db255edd60fce7af34f/lax/lichens/sciencerun0.py#L215): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (97 > 79 characters)
> [Line 216:80](https://github.com/darrylmasson/lax/blob/333a5113a6ff3f7a86a58db255edd60fce7af34f/lax/lichens/sciencerun0.py#L216): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (98 > 79 characters)
> [Line 217:80](https://github.com/darrylmasson/lax/blob/333a5113a6ff3f7a86a58db255edd60fce7af34f/lax/lichens/sciencerun0.py#L217): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (98 > 79 characters)
> [Line 218:80](https://github.com/darrylmasson/lax/blob/333a5113a6ff3f7a86a58db255edd60fce7af34f/lax/lichens/sciencerun0.py#L218): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (99 > 79 characters)
> [Line 221:80](https://github.com/darrylmasson/lax/blob/333a5113a6ff3f7a86a58db255edd60fce7af34f/lax/lichens/sciencerun0.py#L221): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (97 > 79 characters)
> [Line 234:80](https://github.com/darrylmasson/lax/blob/333a5113a6ff3f7a86a58db255edd60fce7af34f/lax/lichens/sciencerun0.py#L234): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (100 > 79 characters)
> [Line 235:80](https://github.com/darrylmasson/lax/blob/333a5113a6ff3f7a86a58db255edd60fce7af34f/lax/lichens/sciencerun0.py#L235): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (108 > 79 characters)
> [Line 236:80](https://github.com/darrylmasson/lax/blob/333a5113a6ff3f7a86a58db255edd60fce7af34f/lax/lichens/sciencerun0.py#L236): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (108 > 79 characters)
> [Line 245:80](https://github.com/darrylmasson/lax/blob/333a5113a6ff3f7a86a58db255edd60fce7af34f/lax/lichens/sciencerun0.py#L245): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 250:80](https://github.com/darrylmasson/lax/blob/333a5113a6ff3f7a86a58db255edd60fce7af34f/lax/lichens/sciencerun0.py#L250): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (84 > 79 characters)
> [Line 266:80](https://github.com/darrylmasson/lax/blob/333a5113a6ff3f7a86a58db255edd60fce7af34f/lax/lichens/sciencerun0.py#L266): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (87 > 79 characters)
> [Line 271:80](https://github.com/darrylmasson/lax/blob/333a5113a6ff3f7a86a58db255edd60fce7af34f/lax/lichens/sciencerun0.py#L271): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (100 > 79 characters)
> [Line 274:80](https://github.com/darrylmasson/lax/blob/333a5113a6ff3f7a86a58db255edd60fce7af34f/lax/lichens/sciencerun0.py#L274): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (100 > 79 characters)
> [Line 287:12](https://github.com/darrylmasson/lax/blob/333a5113a6ff3f7a86a58db255edd60fce7af34f/lax/lichens/sciencerun0.py#L287): [E713](https://duckduckgo.com/?q=pep8%20E713) test for membership should be 'not in'
> [Line 303:80](https://github.com/darrylmasson/lax/blob/333a5113a6ff3f7a86a58db255edd60fce7af34f/lax/lichens/sciencerun0.py#L303): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (94 > 79 characters)
> [Line 304:80](https://github.com/darrylmasson/lax/blob/333a5113a6ff3f7a86a58db255edd60fce7af34f/lax/lichens/sciencerun0.py#L304): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (88 > 79 characters)
> [Line 326:80](https://github.com/darrylmasson/lax/blob/333a5113a6ff3f7a86a58db255edd60fce7af34f/lax/lichens/sciencerun0.py#L326): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 348:80](https://github.com/darrylmasson/lax/blob/333a5113a6ff3f7a86a58db255edd60fce7af34f/lax/lichens/sciencerun0.py#L348): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 355:80](https://github.com/darrylmasson/lax/blob/333a5113a6ff3f7a86a58db255edd60fce7af34f/lax/lichens/sciencerun0.py#L355): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (120 > 79 characters)
> [Line 367:80](https://github.com/darrylmasson/lax/blob/333a5113a6ff3f7a86a58db255edd60fce7af34f/lax/lichens/sciencerun0.py#L367): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (116 > 79 characters)
> [Line 368:80](https://github.com/darrylmasson/lax/blob/333a5113a6ff3f7a86a58db255edd60fce7af34f/lax/lichens/sciencerun0.py#L368): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (111 > 79 characters)
> [Line 372:80](https://github.com/darrylmasson/lax/blob/333a5113a6ff3f7a86a58db255edd60fce7af34f/lax/lichens/sciencerun0.py#L372): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)
> [Line 374:80](https://github.com/darrylmasson/lax/blob/333a5113a6ff3f7a86a58db255edd60fce7af34f/lax/lichens/sciencerun0.py#L374): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (88 > 79 characters)
> [Line 388:80](https://github.com/darrylmasson/lax/blob/333a5113a6ff3f7a86a58db255edd60fce7af34f/lax/lichens/sciencerun0.py#L388) [...]

2017-03-02 17:44 UTC, merged