S2 width cut
XENON1T/lax pull request #18
Opened 2017-02-27 22:29 UTC by weiyuehuan

Diffusion parameters update according to Fig 7 and Fig8 in the note below.
1) 304 -> 350
2) 3.6395 -> 3.9656 (To avoid detail study on diffusion constant and electron drift velocity in limit time, just update this parameter here )
After tuning the parameters, the acceptance inside 99% ER band increased a bit, while the rejection power decreased a bit for the outlier events (Table0 and 1). This decreasing may can be compensated by new S1 pattern cut. Suggested to update to the new parameters. 
https://xecluster.lngs.infn.it/dokuwiki/doku.php?id=xenon:xenon1t:yuehuan:analysis:0sciencerun_s2width_update0#comparison_with_diffusion_model_cut_by_jelle_pax_v642

2017-02-27 22:37 UTC, pdeperio requested changes

2017-02-27 22:37 UTC, pdeperio commented on lax/lichens/sciencerun0.py
>      Author: Jelle, translation to lax by Chris.
Add your name

2017-02-27 22:37 UTC, pdeperio commented on lax/lichens/sciencerun0.py
Replace the Wiki note linked above here, and update the description with what you've done.

2017-02-28 18:12 UTC, tunnell commented
@weiyuehuan also look at Codacy output.  Need to remove trailing whitespace.  After that, I think it's good to go.

2017-02-28 18:13 UTC, tunnell requested changes

2017-02-28 18:13 UTC, tunnell commented on lax/lichens/sciencerun0.py
> +    The S2 width cut compares the S2 width to what we could expect based on its depth in the detector.
Add a line break here and move arXiv link to main body of text.

2017-02-28 19:43 UTC, pdeperio approved these changes

2017-02-28 19:44 UTC, tunnell approved these changes

2017-02-28 19:45 UTC, merged