Lint fixes
XENON1T/lax pull request #25
Opened 2017-03-01 04:25 UTC by tunnell

Codacy followup to address nonuniformity in code from today.

2017-03-01 04:25 UTC, pep8speaks commented
Hello @tunnell! Thanks for submitting the PR.

 - In the file [`examples/lax-root-batch.py`](https://github.com/tunnell/lax/blob/d8e353c5250f63631a558e82dd4948dee3f2c53b/examples/lax-root-batch.py), following are the PEP8 issues :

> [Line 10:28](https://github.com/tunnell/lax/blob/d8e353c5250f63631a558e82dd4948dee3f2c53b/examples/lax-root-batch.py#L10): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 10:30](https://github.com/tunnell/lax/blob/d8e353c5250f63631a558e82dd4948dee3f2c53b/examples/lax-root-batch.py#L10): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 13:26](https://github.com/tunnell/lax/blob/d8e353c5250f63631a558e82dd4948dee3f2c53b/examples/lax-root-batch.py#L13): [E201](https://duckduckgo.com/?q=pep8%20E201) whitespace after '['
> [Line 21:80](https://github.com/tunnell/lax/blob/d8e353c5250f63631a558e82dd4948dee3f2c53b/examples/lax-root-batch.py#L21): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 79 characters)
> [Line 25:18](https://github.com/tunnell/lax/blob/d8e353c5250f63631a558e82dd4948dee3f2c53b/examples/lax-root-batch.py#L25): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','

 - In the file [`lax/__init__.py`](https://github.com/tunnell/lax/blob/d8e353c5250f63631a558e82dd4948dee3f2c53b/lax/__init__.py), following are the PEP8 issues :

> [Line 5:1](https://github.com/tunnell/lax/blob/d8e353c5250f63631a558e82dd4948dee3f2c53b/lax/__init__.py#L5): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file

 - In the file [`lax/cli.py`](https://github.com/tunnell/lax/blob/d8e353c5250f63631a558e82dd4948dee3f2c53b/lax/cli.py), following are the PEP8 issues :

> [Line 21:43](https://github.com/tunnell/lax/blob/d8e353c5250f63631a558e82dd4948dee3f2c53b/lax/cli.py#L21): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent

 - In the file [`lax/lichen.py`](https://github.com/tunnell/lax/blob/d8e353c5250f63631a558e82dd4948dee3f2c53b/lax/lichen.py), following are the PEP8 issues :

> [Line 63:80](https://github.com/tunnell/lax/blob/d8e353c5250f63631a558e82dd4948dee3f2c53b/lax/lichen.py#L63): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 64:9](https://github.com/tunnell/lax/blob/d8e353c5250f63631a558e82dd4948dee3f2c53b/lax/lichen.py#L64): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented
> [Line 99:80](https://github.com/tunnell/lax/blob/d8e353c5250f63631a558e82dd4948dee3f2c53b/lax/lichen.py#L99): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (116 > 79 characters)

 - There are no PEP8 issues in the file [`lax/lichens/__init__.py`](https://github.com/tunnell/lax/blob/d8e353c5250f63631a558e82dd4948dee3f2c53b/lax/lichens/__init__.py) !

 - There are no PEP8 issues in the file [`setup.py`](https://github.com/tunnell/lax/blob/d8e353c5250f63631a558e82dd4948dee3f2c53b/setup.py) !

 - There are no PEP8 issues in the file [`tests/test_variables.py`](https://github.com/tunnell/lax/blob/d8e353c5250f63631a558e82dd4948dee3f2c53b/tests/test_variables.py) !

 - There are no PEP8 issues in the file [`travis_pypi_setup.py`](https://github.com/tunnell/lax/blob/d8e353c5250f63631a558e82dd4948dee3f2c53b/travis_pypi_setup.py) !

2017-03-01 04:48 UTC, pdeperio requested changes

2017-03-01 04:48 UTC, pdeperio commented on examples/lax_root_batch.py
> +PAX_VERSION = '6.4.2'
make these input arguments?

2017-03-01 04:48 UTC, pdeperio commented on examples/lax_root_batch.py
> +                        ['Fundamentals', 'Basics', 'TotalProperties'])
need also ```Extended``` and ```Proximity```?

2017-03-01 06:28 UTC, pdeperio commented on examples/lax_root_batch.py
> +                                                            RUN_NUMBER))
Add second argument to give the tree a more meaningful name than "default", e.g. 
```
, 'cuts'
```

2017-03-02 15:24 UTC, tunnell commented on examples/lax_root_batch.py
> +                                                            RUN_NUMBER))
This didn't work for me when I tried...

2017-03-02 15:24 UTC, tunnell reviewed
Just added comments

2017-03-02 15:28 UTC, tunnell commented on examples/lax_root_batch.py
> +PAX_VERSION = '6.4.2'
Should just make a lax-batch command if you want... I don't think people are using this though and instead just using notebook with hax then writing ROOT file at end.  Maybe could remove this?

2017-03-02 15:30 UTC, pdeperio commented on examples/lax_root_batch.py
> +                                                            RUN_NUMBER))
sorry, you're using the other function. see: https://github.com/ibab/root_pandas#writing-root-files

2017-03-02 15:31 UTC, pdeperio commented on examples/lax_root_batch.py
> +PAX_VERSION = '6.4.2'
would be nice to have a ```lax-batch``` command for data+MC mass productions

2017-03-02 15:33 UTC, pdeperio approved these changes

2017-03-02 15:40 UTC, merged