S1 aft update
XENON1T/lax pull request #32
Opened 2017-03-03 00:08 UTC by darrylmasson

Replaced the pax interpolating map with scipy's RectBivariateSpline. This map is a 2D interpolater, using (r,z) instead of (x,y,z). Differences shouldn't be significant as s1 area fraction top doesn't have strong azimuthal dependence and only varies slowly in space.

Now runs about twice as fast (~2k events/second).

2017-03-03 00:08 UTC, pep8speaks commented
Hello @darrylmasson! Thanks for submitting the PR.

 - In the file [`lax/lichens/sciencerun0.py`](https://github.com/darrylmasson/lax/blob/0474108d415a92f017b76528fe5f016773e5e4ba/lax/lichens/sciencerun0.py), following are the PEP8 issues :

> [Line 16:1](https://github.com/darrylmasson/lax/blob/0474108d415a92f017b76528fe5f016773e5e4ba/lax/lichens/sciencerun0.py#L16): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 17:1](https://github.com/darrylmasson/lax/blob/0474108d415a92f017b76528fe5f016773e5e4ba/lax/lichens/sciencerun0.py#L17): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 21:80](https://github.com/darrylmasson/lax/blob/0474108d415a92f017b76528fe5f016773e5e4ba/lax/lichens/sciencerun0.py#L21): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (98 > 79 characters)
> [Line 89:80](https://github.com/darrylmasson/lax/blob/0474108d415a92f017b76528fe5f016773e5e4ba/lax/lichens/sciencerun0.py#L89): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (87 > 79 characters)
> [Line 94:80](https://github.com/darrylmasson/lax/blob/0474108d415a92f017b76528fe5f016773e5e4ba/lax/lichens/sciencerun0.py#L94): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (86 > 79 characters)
> [Line 125:80](https://github.com/darrylmasson/lax/blob/0474108d415a92f017b76528fe5f016773e5e4ba/lax/lichens/sciencerun0.py#L125): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 79 characters)
> [Line 227:80](https://github.com/darrylmasson/lax/blob/0474108d415a92f017b76528fe5f016773e5e4ba/lax/lichens/sciencerun0.py#L227): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (93 > 79 characters)
> [Line 229:80](https://github.com/darrylmasson/lax/blob/0474108d415a92f017b76528fe5f016773e5e4ba/lax/lichens/sciencerun0.py#L229): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (97 > 79 characters)
> [Line 230:80](https://github.com/darrylmasson/lax/blob/0474108d415a92f017b76528fe5f016773e5e4ba/lax/lichens/sciencerun0.py#L230): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (97 > 79 characters)
> [Line 231:80](https://github.com/darrylmasson/lax/blob/0474108d415a92f017b76528fe5f016773e5e4ba/lax/lichens/sciencerun0.py#L231): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (98 > 79 characters)
> [Line 232:80](https://github.com/darrylmasson/lax/blob/0474108d415a92f017b76528fe5f016773e5e4ba/lax/lichens/sciencerun0.py#L232): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (98 > 79 characters)
> [Line 233:80](https://github.com/darrylmasson/lax/blob/0474108d415a92f017b76528fe5f016773e5e4ba/lax/lichens/sciencerun0.py#L233): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (99 > 79 characters)
> [Line 236:80](https://github.com/darrylmasson/lax/blob/0474108d415a92f017b76528fe5f016773e5e4ba/lax/lichens/sciencerun0.py#L236): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (97 > 79 characters)
> [Line 249:80](https://github.com/darrylmasson/lax/blob/0474108d415a92f017b76528fe5f016773e5e4ba/lax/lichens/sciencerun0.py#L249): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (100 > 79 characters)
> [Line 250:80](https://github.com/darrylmasson/lax/blob/0474108d415a92f017b76528fe5f016773e5e4ba/lax/lichens/sciencerun0.py#L250): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (108 > 79 characters)
> [Line 251:80](https://github.com/darrylmasson/lax/blob/0474108d415a92f017b76528fe5f016773e5e4ba/lax/lichens/sciencerun0.py#L251): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (108 > 79 characters)
> [Line 260:80](https://github.com/darrylmasson/lax/blob/0474108d415a92f017b76528fe5f016773e5e4ba/lax/lichens/sciencerun0.py#L260): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 265:80](https://github.com/darrylmasson/lax/blob/0474108d415a92f017b76528fe5f016773e5e4ba/lax/lichens/sciencerun0.py#L265): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (84 > 79 characters)
> [Line 281:80](https://github.com/darrylmasson/lax/blob/0474108d415a92f017b76528fe5f016773e5e4ba/lax/lichens/sciencerun0.py#L281): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (87 > 79 characters)
> [Line 286:80](https://github.com/darrylmasson/lax/blob/0474108d415a92f017b76528fe5f016773e5e4ba/lax/lichens/sciencerun0.py#L286): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (100 > 79 characters)
> [Line 289:80](https://github.com/darrylmasson/lax/blob/0474108d415a92f017b76528fe5f016773e5e4ba/lax/lichens/sciencerun0.py#L289): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (100 > 79 characters)
> [Line 302:12](https://github.com/darrylmasson/lax/blob/0474108d415a92f017b76528fe5f016773e5e4ba/lax/lichens/sciencerun0.py#L302): [E713](https://duckduckgo.com/?q=pep8%20E713) test for membership should be 'not in'
> [Line 318:80](https://github.com/darrylmasson/lax/blob/0474108d415a92f017b76528fe5f016773e5e4ba/lax/lichens/sciencerun0.py#L318): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (94 > 79 characters)
> [Line 319:80](https://github.com/darrylmasson/lax/blob/0474108d415a92f017b76528fe5f016773e5e4ba/lax/lichens/sciencerun0.py#L319): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (88 > 79 characters)
> [Line 341:80](https://github.com/darrylmasson/lax/blob/0474108d415a92f017b76528fe5f016773e5e4ba/lax/lichens/sciencerun0.py#L341): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 363:80](https://github.com/darrylmasson/lax/blob/0474108d415a92f017b76528fe5f016773e5e4ba/lax/lichens/sciencerun0.py#L363): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 370:80](https://github.com/darrylmasson/lax/blob/0474108d415a92f017b76528fe5f016773e5e4ba/lax/lichens/sciencerun0.py#L370): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (120 > 79 characters)
> [Line 382:80](https://github.com/darrylmasson/lax/blob/0474108d415a92f017b76528fe5f016773e5e4ba/lax/lichens/sciencerun0.py#L382): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (116 > 79 characters)
> [Line 383:80](https://github.com/darrylmasson/lax/blob/0474108d415a92f017b76528fe5f016773e5e4ba/lax/lichens/sciencerun0.py#L383): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (111 > 79 characters)
> [Line 387:80](https://github.com/darrylmasson/lax/blob/0474108d415a92f017b76528fe5f016773e5e4ba/lax/lichens/sciencerun0.py#L387): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)
> [Line 389:80](https://github.com/darrylmasson/lax/blob/0474108d415a92f017b76528fe5f016773e5e4ba/lax/lichens/sciencerun0.py#L389): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (88 > 79 characters)
> [Line 403:80](https://github.com/darrylmasson/lax/blob/0474108d415a92f017b76528fe5f016773e5e4ba/lax/lichens/sciencerun0.py#L403): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (89 > 79 characters)
> [Line 407:80](https://github.com/darrylmasson/lax/blob/0474108d415a92f017b76528fe5f016773e5e4ba/lax/lichens/sciencerun0.py#L407): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 411:80](https://github.com/darrylmasson/lax/blob/0474108d415a92f017b76528fe5f016773e5e4ba/lax/lichens/sciencerun0.py#L411): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 79 characters)
> [Line 428:80](https://github.com/darrylmasson/lax/blob/0474108d415a92f017b76528fe5f016773e5e4ba/lax/lichens/sciencerun0.py#L428): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (88 > 79 characters)
> [Line 429:80](https://github.com/darrylmasson/lax/blob/0474108d415a92f017b76528fe5f016773e5e4ba/lax/lichens/sciencerun0.py#L429): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (95 > 79 characters)
> [Line 438:80](https://github.com/darrylmasson/lax/blob/0474108d415a92f017b76528f [...]

2017-03-03 22:10 UTC, pelssers commented on lax/lichens/sciencerun0.py
> +from scipy.interpolate import RectBiraviateSpline
Typo

2017-03-03 22:13 UTC, darrylmasson commented on lax/lichens/sciencerun0.py
> +from scipy.interpolate import RectBiraviateSpline
So there is.

2017-03-08 00:03 UTC, tunnell requested changes
Fine

2017-03-08 00:03 UTC, tunnell approved these changes

2017-03-08 00:03 UTC, merged