Compatibility with MC
XENON1T/lax pull request #57
Opened 2017-05-23 03:58 UTC by pdeperio

@tunnell can we make this an executable and/or copy to bin?

2017-05-23 04:07 UTC, pdeperio commented
possible to add another flag for each cut indicating whether it's compatible with MC, so that here we just need to pass a single flag instead?

2017-06-05 20:54 UTC, pdeperio commented
Requires https://github.com/XENON1T/hax/issues/47 to be fixed

2017-06-06 14:31 UTC, tunnell requested changes
Looks more or less fine, just small fixes

2017-06-06 14:31 UTC, tunnell commented on examples/lax_root_batch.py
> +                    help='Run number to process (-1 for MC)')
Might want it just to be negative run number for MC.  E.g. -1402 would be SR0 run 1402 in MC etc.  But ok.

2017-06-06 14:31 UTC, tunnell commented on examples/lax_root_batch.py
> +    RUN_NUMBER = args.MINITREE_PATH+'/'+args.FILENAME
os.path.join

2017-06-06 14:31 UTC, tunnell commented on examples/lax_root_batch.py
> +    RUN_NUMBER = args.MINITREE_PATH+'/'+args.FILENAME
and spaces

2017-06-06 14:31 UTC, tunnell commented on examples/lax_root_batch.py
> +    # Remove meaningless cuts (HARDCODE WARNING)
Remove by name.  There is a getname function.

2017-06-06 14:31 UTC, tunnell commented on examples/lax_root_batch.py
> +#HAX_KWARGS['runs_url'] = 'mongodb://eb:{password}@xenon1t-daq.lngs.infn.it:27017/run'
remove

2017-06-06 14:33 UTC, tunnell commented
Disabled travis for future too.

2017-06-06 18:33 UTC, pdeperio commented on examples/lax_root_batch.py
> +                    help='Run number to process (-1 for MC)')
Agree.  But until we get run dependence working at G4/emission/fax/pax level, this doesn't matter.

2017-06-06 18:41 UTC, pdeperio commented on examples/lax_root_batch.py
> +    RUN_NUMBER = args.MINITREE_PATH+'/'+args.FILENAME
This is changed in the [new bin script](https://github.com/XENON1T/lax/blob/d95be1f6fd2f230c2e26fd95ae0724e5c8eaf618/bin/laxer) (this example script will be removed).

2017-06-06 18:42 UTC, pdeperio commented on examples/lax_root_batch.py
> +    # Remove meaningless cuts (HARDCODE WARNING)
Don't understand what you mean here.  Can you write a snippet?

2017-06-06 19:21 UTC, pdeperio commented on examples/lax_root_batch.py
> +    # Remove meaningless cuts (HARDCODE WARNING)
N/m, fixed [here](https://github.com/XENON1T/lax/pull/57/commits/710f2906c3b1f9c053a1581311c8f5f69e354234#diff-e9f87b2a3f5a52d944d1bd9d5651c367R82)

2017-06-06 19:28 UTC, tunnell approved these changes

2017-06-06 19:28 UTC, merged