Created Lichen for ScienceRun1. Updated AmBe FV. Created NG FV
XENON1T/lax pull request #58
Opened 2017-06-06 20:32 UTC by jpienaar13

Corrected definition of AmBe FV in sciencerun0 to reflect the correct source position, as mentioned by Dominic: https://xecluster.lngs.infn.it/dokuwiki/doku.php?id=xenon:xenon1t:analysis:dominick:sr1_ambe_check

Created NG FV. (Not sure if needed, but at least it's there if we do):
https://xecluster.lngs.infn.it/dokuwiki/doku.php?id=xenon:xenon1t:analysis:dominick:ng_early_look

2017-06-07 18:07 UTC, pdeperio requested changes

2017-06-07 18:07 UTC, pdeperio commented on lax/lichens/sciencerun1.py
> +class AmBeFiducial(StringLichen):
Repeated definition?

2017-06-07 22:19 UTC, jpienaar13 commented
Removed the doubled definition

2017-06-08 19:06 UTC, pdeperio submitted a review, later dismissed

2017-06-08 19:08 UTC, pdeperio commented
Should the ```sciencerun0.py``` also be updated with the new AmBe FV?

Also, please click "Details" next to failed "codacy/pr" check, and fix as many as you can.

2017-06-08 19:12 UTC, jpienaar13 commented
Will do. We can update sciencerun0. I see no reason why that would not be a good idea. @andrewgrahambrown any objections

2017-06-19 20:22 UTC, pdeperio requested changes

2017-06-19 20:22 UTC, pdeperio commented on lax/lichens/sciencerun1.py
> +FiducialCylinder1T = sciencerun0.S2Tails
Typo?

2017-06-19 20:22 UTC, pdeperio commented on lax/lichens/sciencerun1.py
> +            SingleElectronS2s()
@feigaodm: is this still needed after https://github.com/XENON1T/pax/pull/576?

If not, I guess we should remove from SR0 lichen too once SR0 gets reprocessed?

2017-06-19 20:23 UTC, pdeperio commented
@jpienaar13 please also commit the AmBe FV SR0 fix to this branch.

2017-06-19 21:06 UTC, jpienaar13 commented on lax/lichens/sciencerun1.py
> +FiducialCylinder1T = sciencerun0.S2Tails
yes, that looks like a typo

2017-06-19 21:08 UTC, jpienaar13 commented
@pdeperio 

Do we want to keep the old incorrect volume, or just update SR0 AmBe fiducial to the correct one?

2017-06-19 21:13 UTC, pdeperio commented
Just update with new version number.

2017-06-19 21:17 UTC, jpienaar13 commented
Done

2017-06-21 15:47 UTC, tunnell commented
@jpienaar13 I think you accidentally introduced style error

2017-06-21 15:52 UTC, jpienaar13 commented
@tunnell That comment is a little cryptic.

2017-06-21 15:58 UTC, tunnell commented
@jpienaar13 do you see how it says that a check had failed?  Also, @pdeperio needs to say if you satisfied the changes requested in the review.  

@jpienaar13 But yeah, you see where it says "All checks have failed", then "codacy/pr", on the right is "details" that takes you here:

https://www.codacy.com/app/weiyuehuan/lax/pullRequest?prid=694964

It's just trailing white space on line 94 so tiny to fix.

2017-06-21 15:58 UTC, tunnell approved these changes

2017-06-21 16:00 UTC, jpienaar13 commented
@tunnell Eh,  I thought I fixed that one yesterday.

2017-06-21 16:08 UTC, tunnell commented
You can just edit the file on the github website.

2017-06-21 16:09 UTC, tunnell commented
https://github.com/XENON1T/lax/edit/ScienceRun1_lichens/lax/lichens/sciencerun1.py?pr=/XENON1T/lax/pull/58

2017-06-21 18:16 UTC, pdeperio approved these changes

2017-06-22 20:14 UTC, pdeperio commented
@tunnell seems like the codacy report doesn't show all the issues at once (they appear one at a time as you fix online).  so i just did ```make lint``` locally and fixed a bunch manually.

2017-06-23 03:43 UTC, merged

2017-11-10 22:42 UTC, pdeperio commented
@jpienaar13: @tunnell noticed that maybe this corrected AmBe FV should have gone into ```sciencerun0``` instead, then inherited here. Is this correct?

2017-11-10 22:54 UTC, jpienaar13 commented
That is correct yes.

2017-11-10 22:58 UTC, pdeperio commented
ah he opened an issue here https://github.com/XENON1T/lax/issues/95