Removed the Calibration Source Classes
XENON1T/lax pull request #86
Opened 2017-10-24 10:59 UTC by sreichard

I removed the 'LowEnergyAmBe' and 'LowEnergyNG' classes but left the original definitions of the FV's designed for the calibration sources, in case someone wants to use them in the future. I also moved S2Tails from 'AllEnergy' to 'LowEnergyBackground', where it belongs.

2017-10-24 20:21 UTC, pdeperio requested changes
Based on @skazama's study [here](https://xe1t-wiki.lngs.infn.it/doku.php?id=xenon:kazama:ambe_ng_comparison:performance_check_ng_ambe#do_we_need_distance_to_source_cut_for_sr1). But did something change in AmBe data from SR0 to SR1 such that we don't need this cut anymore (if not, then we should remove from SR0 too)? Is this consistent with @ErikHogenbirk's [study](https://xecluster.lngs.infn.it/dokuwiki/lib/exe/fetch.php?media=xenon:xenon1t:hogenbirk:nr_band_sr0.html), which first proposed this cut?

@sreichard, you may wish to create a separate PR for ```S2Tails```, so it can be more easily reviewed and merged.

2017-10-25 07:55 UTC, ErikHogenbirk commented
As written in Shingo's [study](https://xe1t-wiki.lngs.infn.it/doku.php?id=xenon:kazama:ambe_ng_comparison:performance_check_ng_ambe#do_we_need_distance_to_source_cut_for_sr1), the ER rate has gone down quite a bit. This was one of the reasons to introduce this cut. The other reason was to remove the events that bleed below the band. From Fig. 1.3 in Shingo's note, it indeed seems that this is not necessary (although it's quite hard to estimate point density -- especially as there are many more purple points). It'd be nicer to see the number of leakage events as a function of distance to source.

So... the FV cuts are still in here? The reason I ask is that we don't necessarily want the same FV for a DM run as for calibration. For calibration, you want to be sure of complete charge collection, a proper functioning posrec, etc. For DM, you want all that AND you want minimal background. This will pose a tighter constraint than you need for calibration, so you may end up throwing out lots of your calibration data (since most events are near the edge) for no reason.

2017-10-25 12:01 UTC, sreichard commented
@ErikHogenbirk Yes, the FV definitions for AmBe and NG still exist in lax. Analysts can access them with the updated version and change them as needed.

2017-10-25 14:03 UTC, jpienaar13 approved these changes

2017-10-25 19:18 UTC, skazama commented
@ErikHogenbirk Concerning FV size, we are currently investigating if we can enlarge FV size for dark matter data, and I'm using 1.3 ton FV also for NR calibration datasets. Its radius is 42.6 cm which is similar size as for SR0 FV cut, so we are not losing statistics. One thing I think we should be careful is that our electric field is not completely uniform, so if we use different FV definitions between dark matter data and calibration data, there could be some differences in the detector responses, so I think it's better to use consistent FV size (although NR has less dependency on field from NEST model).

2017-10-27 14:23 UTC, pdeperio approved these changes

2017-10-27 14:24 UTC, merged

2017-11-10 22:47 UTC, pdeperio commented
@tunnell mentions that would be nice to keep the ```LowEnergyAmBe``` and ```LowEnergyNG``` class definitions for backward compatibility, and just not apply them to data. (Also, they're still defined in ```sciencerun0.py```, which should have also been removed for consistency.)

Also, it's not clear now what to apply to AmBe/NG, since we still explicitly have ```LowEnergyBackground``` and ```LowEnergyRn220```.

2017-11-10 22:48 UTC, tunnell commented
See #95